#!/bin/bash

LATEX_OPTIONS='-file-line-error -halt-on-error'
ARCHIVOS=$(find . -name "*.tex")
ARCHIVOS_BORRAR='*.aux *.log'

for file in $ARCHIVOS; do
	echo -n "Compilando archivo $file..."
        if (! pdflatex $LATEX_OPTIONS $file > /dev/null); then
		echo -n " ¡Error al compilar!"
	else
		echo -n " Ok"
	fi

	echo
done

echo "Eliminando archivos generados por LaTeX ($ARCHIVOS_BORRAR)"
rm -rf $ARCHIVOS_BORRAR

